// import type { Metadata } from "next";
// import "./globals.css";
// import Providers from "@/providers";
// import { Toaster } from "react-hot-toast";
// // import Navbar from "@/components/shared/Navbar";
// // import { getServerSession } from "next-auth";
// // import Footer from "@/components/shared/Footer";

// export const metadata: Metadata = {
//   title: "Next Auth",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   // const session = await getServerSession();

//   return (
//     <html lang="en" data-theme="light">
//       <body cz-shortcut-listen="true">
//         {/* <Navbar  session={session}/> */}
//         <Providers>
//         <div className="min-h-screen" suppressHydrationWarning>{children}</div>
//         <Toaster position="top-center" reverseOrder={false} />
//         </Providers>
//         {/* <Footer></Footer> */}
//       </body>
//     </html>
//   );
// }







import type { Metadata } from "next";
import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import { Toaster } from "react-hot-toast";

const display = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["400", "500", "600", "700"],
});

const body = Manrope({
  subsets: ["latin"],
  variable: "--font-body",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Naeem | Portfolio",
  description: "Minimal, elegant portfolio and project showcase.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable}`}>
      <body
        className="bg-[#f6f1ea] text-slate-900 antialiased selection:bg-[#f2c6a0] selection:text-slate-900"
        suppressHydrationWarning
      >
        <Providers>
          <div className="min-h-screen">{children}</div>
          <Toaster position="top-center" reverseOrder={false} />
        </Providers>
      </body>
    </html>
  );
}
